name: Create Release

on:
  push:
    tags:
      - 'v*'  # Push events to tags matching v*, i.e., v1.0.0, v20.15.10

permissions:
  contents: write

jobs:
  build:
    name: Build and Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyproject_hooks packaging
          pip install --no-deps build twine
          
      - name: Build package
        run: |
          python -m build
          ls -la dist/  # Debug: Check what files are actually built
          
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/*.tar.gz  # Use a more flexible pattern to match the tarball
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false